; pokemon ids
; indexes for:
; - MonsterNames (see data/pokemon/names.asm)
; - EvosMovesPointerTable (see data/pokemon/evos_moves.asm)
; - CryData (see data/pokemon/cries.asm)
; - PokedexOrder (see data/pokemon/dex_order.asm)
; - PokedexEntryPointers (see data/pokemon/dex_entries.asm)
	const_def
	const NO_MON             ; $00
	const RHYDON             ; $01
	const KANGASKHAN         ; $02
	const NIDORAN_M          ; $03
	const CLEFAIRY           ; $04
	const SPEAROW            ; $05
	const VOLTORB            ; $06
	const NIDOKING           ; $07
	const SLOWBRO            ; $08
	const IVYSAUR            ; $09
	const EXEGGUTOR          ; $0A
	const LICKITUNG          ; $0B
	const EXEGGCUTE          ; $0C
	const GRIMER             ; $0D
	const GENGAR             ; $0E
	const NIDORAN_F          ; $0F
	const NIDOQUEEN          ; $10
	const CUBONE             ; $11
	const RHYHORN            ; $12
	const LAPRAS             ; $13
	const ARCANINE           ; $14
	const MEW                ; $15
	const GYARADOS           ; $16
	const SHELLDER           ; $17
	const TENTACOOL          ; $18
	const GASTLY             ; $19
	const SCYTHER            ; $1A
	const STARYU             ; $1B
	const BLASTOISE          ; $1C
	const PINSIR             ; $1D
	const TANGELA            ; $1E
	const CHIKORITA        ; $20
	const BAYLEEF          ; $21
	const GROWLITHE          ; $21
	const ONIX               ; $22
	const FEAROW             ; $23
	const PIDGEY             ; $24
	const SLOWPOKE           ; $25
	const KADABRA            ; $26
	const GRAVELER           ; $27
	const CHANSEY            ; $28
	const MACHOKE            ; $29
	const MR_MIME            ; $2A
	const HITMONLEE          ; $2B
	const HITMONCHAN         ; $2C
	const ARBOK              ; $2D
	const PARASECT           ; $2E
	const PSYDUCK            ; $2F
	const DROWZEE            ; $30
	const GOLEM              ; $31
	const MEGANIUM         ; $33
	const MAGMAR             ; $33
	const CYNDAQUIL        ; $35
	const ELECTABUZZ         ; $35
	const MAGNETON           ; $36
	const KOFFING            ; $37
	const QUILAVA          ; $39
	const MANKEY             ; $39
	const SEEL               ; $3A
	const DIGLETT            ; $3B
	const TAUROS             ; $3C
	const TYPHLOSION       ; $3E
	const TOTODILE         ; $3F
	const CROCONAW         ; $40
	const FARFETCHD          ; $40
	const VENONAT            ; $41
	const DRAGONITE          ; $42
	const FERALIGATR       ; $44
	const SENTRET          ; $45
	const FURRET           ; $46
	const DODUO              ; $46
	const POLIWAG            ; $47
	const JYNX               ; $48
	const MOLTRES            ; $49
	const ARTICUNO           ; $4A
	const ZAPDOS             ; $4B
	const DITTO              ; $4C
	const MEOWTH             ; $4D
	const KRABBY             ; $4E
	const HOOTHOOT         ; $50
	const NOCTOWL          ; $51
	const LEDYBA           ; $52
	const VULPIX             ; $52
	const NINETALES          ; $53
	const PIKACHU            ; $54
	const RAICHU             ; $55
	const LEDIAN           ; $57
	const SPINARAK         ; $58
	const DRATINI            ; $58
	const DRAGONAIR          ; $59
	const KABUTO             ; $5A
	const KABUTOPS           ; $5B
	const HORSEA             ; $5C
	const SEADRA             ; $5D
	const ARIADOS          ; $5F
	const CROBAT           ; $60
	const SANDSHREW          ; $60
	const SANDSLASH          ; $61
	const OMANYTE            ; $62
	const OMASTAR            ; $63
	const JIGGLYPUFF         ; $64
	const WIGGLYTUFF         ; $65
	const EEVEE              ; $66
	const FLAREON            ; $67
	const JOLTEON            ; $68
	const VAPOREON           ; $69
	const MACHOP             ; $6A
	const ZUBAT              ; $6B
	const EKANS              ; $6C
	const PARAS              ; $6D
	const POLIWHIRL          ; $6E
	const POLIWRATH          ; $6F
	const WEEDLE             ; $70
	const KAKUNA             ; $71
	const BEEDRILL           ; $72
	const CHINCHOU         ; $74
	const DODRIO             ; $74
	const PRIMEAPE           ; $75
	const DUGTRIO            ; $76
	const VENOMOTH           ; $77
	const DEWGONG            ; $78
	const LANTURN          ; $7A
	const PICHU            ; $7B
	const CATERPIE           ; $7B
	const METAPOD            ; $7C
	const BUTTERFREE         ; $7D
	const MACHAMP            ; $7E
	const CLEFFA           ; $80
	const GOLDUCK            ; $80
	const HYPNO              ; $81
	const GOLBAT             ; $82
	const MEWTWO             ; $83
	const SNORLAX            ; $84
	const MAGIKARP           ; $85
	const IGGLYBUFF        ; $87
	const TOGEPI           ; $88
	const MUK                ; $88
	const TOGETIC          ; $8A
	const KINGLER            ; $8A
	const CLOYSTER           ; $8B
	const NATU             ; $8D
	const ELECTRODE          ; $8D
	const CLEFABLE           ; $8E
	const WEEZING            ; $8F
	const PERSIAN            ; $90
	const MAROWAK            ; $91
	const XATU             ; $93
	const HAUNTER            ; $93
	const ABRA               ; $94
	const ALAKAZAM           ; $95
	const PIDGEOTTO          ; $96
	const PIDGEOT            ; $97
	const STARMIE            ; $98
	const BULBASAUR          ; $99
	const VENUSAUR           ; $9A
	const TENTACRUEL         ; $9B
	const MAREEP           ; $9D
	const GOLDEEN            ; $9D
	const SEAKING            ; $9E
	const FLAAFFY          ; $A0
	const AMPHAROS         ; $A1
	const BELLOSSOM        ; $A2
	const MARILL           ; $A3
	const PONYTA             ; $A3
	const RAPIDASH           ; $A4
	const RATTATA            ; $A5
	const RATICATE           ; $A6
	const NIDORINO           ; $A7
	const NIDORINA           ; $A8
	const GEODUDE            ; $A9
	const PORYGON            ; $AA
	const AERODACTYL         ; $AB
	const AZUMARILL        ; $AD
	const MAGNEMITE          ; $AD
	const SUDOWOODO        ; $AF
	const POLITOED         ; $B0
	const CHARMANDER         ; $B0
	const SQUIRTLE           ; $B1
	const CHARMELEON         ; $B2
	const WARTORTLE          ; $B3
	const CHARIZARD          ; $B4
	const HOPPIP           ; $B6
	const FOSSIL_KABUTOPS    ; $B6
	const FOSSIL_AERODACTYL  ; $B7
	const MON_GHOST          ; $B8
	const ODDISH             ; $B9
	const GLOOM              ; $BA
	const VILEPLUME          ; $BB
	const BELLSPROUT         ; $BC
	const WEEPINBELL         ; $BD
	const VICTREEBEL         ; $BE

; === BEGIN GEN2 IMPORT (generated by tools/gen2_emit.py) ===
	const SKIPLOOM         ; $BF
	const JUMPLUFF         ; $C0
	const AIPOM            ; $C1
	const SUNKERN          ; $C2
	const SUNFLORA         ; $C3
	const YANMA            ; $C4
	const WOOPER           ; $C5
	const QUAGSIRE         ; $C6
	const ESPEON           ; $C7
	const SLOWKING         ; $C8
	const MISDREAVUS       ; $C9
	const WOBBUFFET        ; $CA
	const GIRAFARIG        ; $CB
	const PINECO           ; $CC
	const DUNSPARCE        ; $CD
	const GLIGAR           ; $CE
	const SNUBBULL         ; $CF
	const GRANBULL         ; $D0
	const QWILFISH         ; $D1
	const SHUCKLE          ; $D2
	const HERACROSS        ; $D3
	const TEDDIURSA        ; $D4
	const URSARING         ; $D5
	const SLUGMA           ; $D6
	const MAGCARGO         ; $D7
	const SWINUB           ; $D8
	const PILOSWINE        ; $D9
	const CORSOLA          ; $DA
	const REMORAID         ; $DB
	const OCTILLERY        ; $DC
	const DELIBIRD         ; $DD
	const MANTINE          ; $DE
	const KINGDRA          ; $DF
	const PHANPY           ; $E0
	const DONPHAN          ; $E1
	const PORYGON2         ; $E2
	const STANTLER         ; $E3
	const SMEARGLE         ; $E4
	const TYROGUE          ; $E5
	const HITMONTOP        ; $E6
	const SMOOCHUM         ; $E7
	const ELEKID           ; $E8
	const MAGBY            ; $E9
	const MILTANK          ; $EA
	const BLISSEY          ; $EB
	const RAIKOU           ; $EC
	const ENTEI            ; $ED
	const SUICUNE          ; $EE
	const LARVITAR         ; $EF
	const PUPITAR          ; $F0
	const LUGIA            ; $F1
	const HO_OH            ; $F2
	const CELEBI           ; $F3
; === END GEN2 IMPORT ===
DEF NUM_POKEMON_INDEXES EQU const_value - 1

; starters
DEF STARTER1 EQU CHARMANDER
DEF STARTER2 EQU SQUIRTLE
DEF STARTER3 EQU BULBASAUR

; ghost Marowak in Pokémon Tower
DEF RESTLESS_SOUL EQU MAROWAK
