; Generated by tools/gen2_emit.py -- do not edit by hand.
; Sprite ROM bank for each species, indexed by INTERNAL INDEX.
; MEW and the fossil/ghost pics are special-cased in
; home/pics.asm before this table is consulted.
MonPicBanks::
	table_width 1
	db 0 ; $00 NO_MON (no pic)
	db BANK("Pics 1") ; $01 RHYDON
	db BANK("Pics 1") ; $02 KANGASKHAN
	db BANK("Pics 1") ; $03 NIDORAN_M
	db BANK("Pics 1") ; $04 CLEFAIRY
	db BANK("Pics 1") ; $05 SPEAROW
	db BANK("Pics 1") ; $06 VOLTORB
	db BANK("Pics 1") ; $07 NIDOKING
	db BANK("Pics 1") ; $08 SLOWBRO
	db BANK("Pics 1") ; $09 IVYSAUR
	db BANK("Pics 1") ; $0A EXEGGUTOR
	db BANK("Pics 1") ; $0B LICKITUNG
	db BANK("Pics 1") ; $0C EXEGGCUTE
	db BANK("Pics 1") ; $0D GRIMER
	db BANK("Pics 1") ; $0E GENGAR
	db BANK("Pics 1") ; $0F NIDORAN_F
	db BANK("Pics 1") ; $10 NIDOQUEEN
	db BANK("Pics 1") ; $11 CUBONE
	db BANK("Pics 1") ; $12 RHYHORN
	db BANK("Pics 1") ; $13 LAPRAS
	db BANK("Pics 1") ; $14 ARCANINE
	db BANK("Pics 1") ; $15 MEW
	db BANK("Pics 1") ; $16 GYARADOS
	db BANK("Pics 1") ; $17 SHELLDER
	db BANK("Pics 1") ; $18 TENTACOOL
	db BANK("Pics 1") ; $19 GASTLY
	db BANK("Pics 1") ; $1A SCYTHER
	db BANK("Pics 1") ; $1B STARYU
	db BANK("Pics 1") ; $1C BLASTOISE
	db BANK("Pics 1") ; $1D PINSIR
	db BANK("Pics 1") ; $1E TANGELA
	db BANK("Pics Gen2 1") ; $1F CHIKORITA
	db BANK("Pics Gen2 1") ; $20 BAYLEEF
	db BANK("Pics 2") ; $21 GROWLITHE
	db BANK("Pics 2") ; $22 ONIX
	db BANK("Pics 2") ; $23 FEAROW
	db BANK("Pics 2") ; $24 PIDGEY
	db BANK("Pics 2") ; $25 SLOWPOKE
	db BANK("Pics 2") ; $26 KADABRA
	db BANK("Pics 2") ; $27 GRAVELER
	db BANK("Pics 2") ; $28 CHANSEY
	db BANK("Pics 2") ; $29 MACHOKE
	db BANK("Pics 2") ; $2A MR_MIME
	db BANK("Pics 2") ; $2B HITMONLEE
	db BANK("Pics 2") ; $2C HITMONCHAN
	db BANK("Pics 2") ; $2D ARBOK
	db BANK("Pics 2") ; $2E PARASECT
	db BANK("Pics 2") ; $2F PSYDUCK
	db BANK("Pics 2") ; $30 DROWZEE
	db BANK("Pics 2") ; $31 GOLEM
	db BANK("Pics Gen2 1") ; $32 MEGANIUM
	db BANK("Pics 2") ; $33 MAGMAR
	db BANK("Pics Gen2 1") ; $34 CYNDAQUIL
	db BANK("Pics 2") ; $35 ELECTABUZZ
	db BANK("Pics 2") ; $36 MAGNETON
	db BANK("Pics 2") ; $37 KOFFING
	db BANK("Pics Gen2 1") ; $38 QUILAVA
	db BANK("Pics 2") ; $39 MANKEY
	db BANK("Pics 2") ; $3A SEEL
	db BANK("Pics 2") ; $3B DIGLETT
	db BANK("Pics 2") ; $3C TAUROS
	db BANK("Pics Gen2 1") ; $3D TYPHLOSION
	db BANK("Pics Gen2 1") ; $3E TOTODILE
	db BANK("Pics Gen2 1") ; $3F CROCONAW
	db BANK("Pics 2") ; $40 FARFETCHD
	db BANK("Pics 2") ; $41 VENONAT
	db BANK("Pics 2") ; $42 DRAGONITE
	db BANK("Pics Gen2 1") ; $43 FERALIGATR
	db BANK("Pics Gen2 1") ; $44 SENTRET
	db BANK("Pics Gen2 1") ; $45 FURRET
	db BANK("Pics 2") ; $46 DODUO
	db BANK("Pics 2") ; $47 POLIWAG
	db BANK("Pics 2") ; $48 JYNX
	db BANK("Pics 2") ; $49 MOLTRES
	db BANK("Pics 3") ; $4A ARTICUNO
	db BANK("Pics 3") ; $4B ZAPDOS
	db BANK("Pics 3") ; $4C DITTO
	db BANK("Pics 3") ; $4D MEOWTH
	db BANK("Pics 3") ; $4E KRABBY
	db BANK("Pics Gen2 1") ; $4F HOOTHOOT
	db BANK("Pics Gen2 1") ; $50 NOCTOWL
	db BANK("Pics Gen2 1") ; $51 LEDYBA
	db BANK("Pics 3") ; $52 VULPIX
	db BANK("Pics 3") ; $53 NINETALES
	db BANK("Pics 3") ; $54 PIKACHU
	db BANK("Pics 3") ; $55 RAICHU
	db BANK("Pics Gen2 1") ; $56 LEDIAN
	db BANK("Pics Gen2 2") ; $57 SPINARAK
	db BANK("Pics 3") ; $58 DRATINI
	db BANK("Pics 3") ; $59 DRAGONAIR
	db BANK("Pics 3") ; $5A KABUTO
	db BANK("Pics 3") ; $5B KABUTOPS
	db BANK("Pics 3") ; $5C HORSEA
	db BANK("Pics 3") ; $5D SEADRA
	db BANK("Pics Gen2 2") ; $5E ARIADOS
	db BANK("Pics Gen2 2") ; $5F CROBAT
	db BANK("Pics 3") ; $60 SANDSHREW
	db BANK("Pics 3") ; $61 SANDSLASH
	db BANK("Pics 3") ; $62 OMANYTE
	db BANK("Pics 3") ; $63 OMASTAR
	db BANK("Pics 3") ; $64 JIGGLYPUFF
	db BANK("Pics 3") ; $65 WIGGLYTUFF
	db BANK("Pics 3") ; $66 EEVEE
	db BANK("Pics 3") ; $67 FLAREON
	db BANK("Pics 3") ; $68 JOLTEON
	db BANK("Pics 3") ; $69 VAPOREON
	db BANK("Pics 3") ; $6A MACHOP
	db BANK("Pics 3") ; $6B ZUBAT
	db BANK("Pics 3") ; $6C EKANS
	db BANK("Pics 3") ; $6D PARAS
	db BANK("Pics 3") ; $6E POLIWHIRL
	db BANK("Pics 3") ; $6F POLIWRATH
	db BANK("Pics 3") ; $70 WEEDLE
	db BANK("Pics 3") ; $71 KAKUNA
	db BANK("Pics 3") ; $72 BEEDRILL
	db BANK("Pics Gen2 2") ; $73 CHINCHOU
	db BANK("Pics 4") ; $74 DODRIO
	db BANK("Pics 4") ; $75 PRIMEAPE
	db BANK("Pics 4") ; $76 DUGTRIO
	db BANK("Pics 4") ; $77 VENOMOTH
	db BANK("Pics 4") ; $78 DEWGONG
	db BANK("Pics Gen2 2") ; $79 LANTURN
	db BANK("Pics Gen2 2") ; $7A PICHU
	db BANK("Pics 4") ; $7B CATERPIE
	db BANK("Pics 4") ; $7C METAPOD
	db BANK("Pics 4") ; $7D BUTTERFREE
	db BANK("Pics 4") ; $7E MACHAMP
	db BANK("Pics Gen2 2") ; $7F CLEFFA
	db BANK("Pics 4") ; $80 GOLDUCK
	db BANK("Pics 4") ; $81 HYPNO
	db BANK("Pics 4") ; $82 GOLBAT
	db BANK("Pics 4") ; $83 MEWTWO
	db BANK("Pics 4") ; $84 SNORLAX
	db BANK("Pics 4") ; $85 MAGIKARP
	db BANK("Pics Gen2 2") ; $86 IGGLYBUFF
	db BANK("Pics Gen2 2") ; $87 TOGEPI
	db BANK("Pics 4") ; $88 MUK
	db BANK("Pics Gen2 2") ; $89 TOGETIC
	db BANK("Pics 4") ; $8A KINGLER
	db BANK("Pics 4") ; $8B CLOYSTER
	db BANK("Pics Gen2 2") ; $8C NATU
	db BANK("Pics 4") ; $8D ELECTRODE
	db BANK("Pics 4") ; $8E CLEFABLE
	db BANK("Pics 4") ; $8F WEEZING
	db BANK("Pics 4") ; $90 PERSIAN
	db BANK("Pics 4") ; $91 MAROWAK
	db BANK("Pics Gen2 2") ; $92 XATU
	db BANK("Pics 4") ; $93 HAUNTER
	db BANK("Pics 4") ; $94 ABRA
	db BANK("Pics 4") ; $95 ALAKAZAM
	db BANK("Pics 4") ; $96 PIDGEOTTO
	db BANK("Pics 4") ; $97 PIDGEOT
	db BANK("Pics 4") ; $98 STARMIE
	db BANK("Pics 5") ; $99 BULBASAUR
	db BANK("Pics 5") ; $9A VENUSAUR
	db BANK("Pics 5") ; $9B TENTACRUEL
	db BANK("Pics Gen2 2") ; $9C MAREEP
	db BANK("Pics 5") ; $9D GOLDEEN
	db BANK("Pics 5") ; $9E SEAKING
	db BANK("Pics Gen2 2") ; $9F FLAAFFY
	db BANK("Pics Gen2 2") ; $A0 AMPHAROS
	db BANK("Pics Gen2 3") ; $A1 BELLOSSOM
	db BANK("Pics Gen2 3") ; $A2 MARILL
	db BANK("Pics 5") ; $A3 PONYTA
	db BANK("Pics 5") ; $A4 RAPIDASH
	db BANK("Pics 5") ; $A5 RATTATA
	db BANK("Pics 5") ; $A6 RATICATE
	db BANK("Pics 5") ; $A7 NIDORINO
	db BANK("Pics 5") ; $A8 NIDORINA
	db BANK("Pics 5") ; $A9 GEODUDE
	db BANK("Pics 5") ; $AA PORYGON
	db BANK("Pics 5") ; $AB AERODACTYL
	db BANK("Pics Gen2 3") ; $AC AZUMARILL
	db BANK("Pics 5") ; $AD MAGNEMITE
	db BANK("Pics Gen2 3") ; $AE SUDOWOODO
	db BANK("Pics Gen2 3") ; $AF POLITOED
	db BANK("Pics 5") ; $B0 CHARMANDER
	db BANK("Pics 5") ; $B1 SQUIRTLE
	db BANK("Pics 5") ; $B2 CHARMELEON
	db BANK("Pics 5") ; $B3 WARTORTLE
	db BANK("Pics 5") ; $B4 CHARIZARD
	db BANK("Pics Gen2 3") ; $B5 HOPPIP
	db BANK("Pics 5") ; $B6 FOSSIL_KABUTOPS
	db BANK("Pics 5") ; $B7 FOSSIL_AERODACTYL
	db BANK("Pics 5") ; $B8 MON_GHOST
	db BANK("Pics 5") ; $B9 ODDISH
	db BANK("Pics 5") ; $BA GLOOM
	db BANK("Pics 5") ; $BB VILEPLUME
	db BANK("Pics 5") ; $BC BELLSPROUT
	db BANK("Pics 5") ; $BD WEEPINBELL
	db BANK("Pics 5") ; $BE VICTREEBEL
	db BANK("Pics Gen2 3") ; $BF SKIPLOOM
	db BANK("Pics Gen2 3") ; $C0 JUMPLUFF
	db BANK("Pics Gen2 3") ; $C1 AIPOM
	db BANK("Pics Gen2 3") ; $C2 SUNKERN
	db BANK("Pics Gen2 3") ; $C3 SUNFLORA
	db BANK("Pics Gen2 3") ; $C4 YANMA
	db BANK("Pics Gen2 3") ; $C5 WOOPER
	db BANK("Pics Gen2 3") ; $C6 QUAGSIRE
	db BANK("Pics Gen2 3") ; $C7 ESPEON
	db BANK("Pics Gen2 4") ; $C8 SLOWKING
	db BANK("Pics Gen2 4") ; $C9 MISDREAVUS
	db BANK("Pics Gen2 4") ; $CA WOBBUFFET
	db BANK("Pics Gen2 4") ; $CB GIRAFARIG
	db BANK("Pics Gen2 4") ; $CC PINECO
	db BANK("Pics Gen2 4") ; $CD DUNSPARCE
	db BANK("Pics Gen2 4") ; $CE GLIGAR
	db BANK("Pics Gen2 4") ; $CF SNUBBULL
	db BANK("Pics Gen2 4") ; $D0 GRANBULL
	db BANK("Pics Gen2 4") ; $D1 QWILFISH
	db BANK("Pics Gen2 4") ; $D2 SHUCKLE
	db BANK("Pics Gen2 4") ; $D3 HERACROSS
	db BANK("Pics Gen2 4") ; $D4 TEDDIURSA
	db BANK("Pics Gen2 4") ; $D5 URSARING
	db BANK("Pics Gen2 4") ; $D6 SLUGMA
	db BANK("Pics Gen2 5") ; $D7 MAGCARGO
	db BANK("Pics Gen2 5") ; $D8 SWINUB
	db BANK("Pics Gen2 5") ; $D9 PILOSWINE
	db BANK("Pics Gen2 5") ; $DA CORSOLA
	db BANK("Pics Gen2 5") ; $DB REMORAID
	db BANK("Pics Gen2 5") ; $DC OCTILLERY
	db BANK("Pics Gen2 5") ; $DD DELIBIRD
	db BANK("Pics Gen2 5") ; $DE MANTINE
	db BANK("Pics Gen2 5") ; $DF KINGDRA
	db BANK("Pics Gen2 5") ; $E0 PHANPY
	db BANK("Pics Gen2 5") ; $E1 DONPHAN
	db BANK("Pics Gen2 5") ; $E2 PORYGON2
	db BANK("Pics Gen2 5") ; $E3 STANTLER
	db BANK("Pics Gen2 5") ; $E4 SMEARGLE
	db BANK("Pics Gen2 5") ; $E5 TYROGUE
	db BANK("Pics Gen2 6") ; $E6 HITMONTOP
	db BANK("Pics Gen2 6") ; $E7 SMOOCHUM
	db BANK("Pics Gen2 6") ; $E8 ELEKID
	db BANK("Pics Gen2 6") ; $E9 MAGBY
	db BANK("Pics Gen2 6") ; $EA MILTANK
	db BANK("Pics Gen2 6") ; $EB BLISSEY
	db BANK("Pics Gen2 6") ; $EC RAIKOU
	db BANK("Pics Gen2 6") ; $ED ENTEI
	db BANK("Pics Gen2 6") ; $EE SUICUNE
	db BANK("Pics Gen2 6") ; $EF LARVITAR
	db BANK("Pics Gen2 6") ; $F0 PUPITAR
	db BANK("Pics Gen2 6") ; $F1 LUGIA
	db BANK("Pics Gen2 6") ; $F2 HO_OH
	db BANK("Pics Gen2 6") ; $F3 CELEBI
	assert_table_length NUM_POKEMON_INDEXES + 1
