"""
Cross-check EVERY species constant against the name table actually built into
the ROM. Static-only: reads constants/pokemon_constants.asm and MonsterNames
straight out of pokered.gbc.

This is the test that would have caught the off-by-one that shipped in v0.27.
`const_def` (no argument) starts the counter at 0 and NO_MON legitimately takes
index $00, so a generator that starts counting at 0 puts every index one slot
too high. The constants file still LOOKED right (its own comments were
generated by the same broken walker) and the build was clean -- only comparing
constants against the real name-table bytes exposes it. Symptom in play was
"Wild MISSINGNO. appeared" plus wrong names on unrelated Gen 1 species.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def species_constants():
    """-> {index: CONST_NAME}, derived the same way rgbasm does."""
    path = os.path.join(ROOT, "constants/pokemon_constants.asm")
    out = {}
    val = -1
    for line in open(path, encoding="utf-8"):
        s = line.strip()
        if s.startswith("const_def"):
            m = re.match(r"const_def\s+(\d+)", s)
            val = (int(m.group(1)) - 1) if m else -1
            continue
        if s.startswith("const_next"):
            val = int(re.search(r"\$([0-9A-Fa-f]+)", s).group(1)) - 1
            continue
        if s.startswith("const_skip"):
            val += 1
            continue
        m = re.match(r"const\s+([A-Z_0-9]+)", s)
        if m:
            val += 1
            out[val] = m.group(1)
    return out


def monster_names():
    """-> {index: NAME} decoded from the built ROM."""
    sym = {}
    for line in open(os.path.join(ROOT, "pokered.sym"), encoding="utf-8"):
        m = re.match(r"([0-9a-f]{2}):([0-9a-f]{4}) (\S+)", line.strip())
        if m:
            sym[m.group(3)] = (int(m.group(1), 16), int(m.group(2), 16))
    bank, addr = sym["MonsterNames"]
    rom = open(os.path.join(ROOT, "pokered.gbc"), "rb").read()
    off = bank * 0x4000 + (addr - 0x4000)

    def dec(b):
        o = []
        for c in b:
            if c == 0x50:
                break
            if 0x80 <= c <= 0x99:
                o.append(chr(65 + c - 0x80))
            elif 0xA0 <= c <= 0xB9:
                o.append(chr(97 + c - 0xA0))
            elif c == 0xE3:
                o.append("-")
            elif c == 0xEF:
                o.append("M")
            elif c == 0xF5:
                o.append("F")
            elif c == 0xE6 or c == 0xF2:
                o.append(".")
            elif 0xF6 <= c <= 0xFF:  # digits '0'-'9', e.g. PORYGON2
                o.append(chr(ord("0") + c - 0xF6))
            elif c == 0x7F:
                o.append(" ")
            else:
                o.append("?")
        return "".join(o).strip()

    # Entry N (1-based) is internal index N; NO_MON ($00) has no name entry.
    return {i: dec(rom[off + (i - 1) * 10:off + (i - 1) * 10 + 10])
            for i in range(1, 244)}


def norm(s):
    return re.sub(r"[^A-Z0-9]", "", s.upper())


def main():
    consts = species_constants()
    names = monster_names()

    # These three are genuinely named "MISSINGNO." in vanilla and are not species.
    EXEMPT = {"FOSSIL_KABUTOPS", "FOSSIL_AERODACTYL", "MON_GHOST"}

    bad = []
    for idx, const in sorted(consts.items()):
        if idx == 0 or const in EXEMPT:
            continue
        name = names.get(idx, "")
        if norm(name) != norm(const):
            bad.append((idx, const, name))

    # Any index that has a name but no constant is a leftover hole.
    holes = [i for i, n in names.items()
             if "MISSINGNO" in n and consts.get(i) not in EXEMPT
             and i in consts]

    print(f"species constants checked : {len(consts) - 1}")
    print(f"name mismatches           : {len(bad)}")
    for idx, const, name in bad[:15]:
        print(f"  ${idx:02X}: constant {const:<14} but name table says {name!r}")
    print(f"constants still reading MISSINGNO: {len(holes)}")
    for i in holes[:10]:
        print(f"  ${i:02X}: {consts[i]}")

    ok = not bad and not holes
    print("\nPASS: every species constant matches its name-table entry"
          if ok else "\nFAIL: species tables are misaligned")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
