#!/usr/bin/env python3
"""
Victorian-gothic Pokedex prose for the 89 imported Gen 2 species.

Replaces the raw Gen 2 flavour text the importer originally carried over.
Tone follows the project's established register (archaic diction, mourning and
decay, class-conscious cruelty, plain menace) -- see CLAUDE.md item 2.

FORMAT: slug -> [page1_lines, page2_lines]. Each page is up to 3 lines and is
rendered as `text`/`next`/`next` then `page`/`next`/`next`.

HARD CONSTRAINT: every line must be <= 18 visible characters. The text box is 20
tiles wide but the game does not reject overlong lines -- it wraps mid-word and
truncates, which is a bug that only shows up in a screenshot. Enforced by
tools/tests/test_dex_line_budget.py, which fails the suite rather than trusting
these by eye.
"""

DEX = {
# --- Johto starters ---------------------------------------------------------
"chikorita": [["The leaf at its", "neck wilts when", "it senses grief."],
              ["Gardeners call it", "a mourner's herb."]],
"bayleef": [["Its spiced breath", "revives the faint", "and the dying."],
            ["Physicians covet", "what it exhales."]],
"meganium": [["Where it treads,", "dead soil wakes.", "Where it grieves,"],
             ["the blossoms rot", "within the hour."]],
"cyndaquil": [["Timid. Its back", "smoulders only", "when frightened."],
              ["Cornered, it has", "burned down barns."]],
"quilava": [["It shows its back", "to no one. The", "flame is warning."],
            ["Approach, and it", "warns but once."]],
"typhlosion": [["It hides behind", "shimmering heat,", "then the field is"],
               ["ash, and nothing", "cries out at all."]],
"totodile": [["It bites for the", "joy of biting.", "It knows no other"],
             ["affection than", "the closing jaw."]],
"croconaw": [["Its fangs, once", "sunk, will not", "loose. They snap"],
             ["before they yield,", "and grow again."]],
"feraligatr": [["It drags what it", "takes below, and", "waits. Patience"],
               ["is the cruellest", "part of the hunt."]],
# --- early routes -----------------------------------------------------------
"sentret": [["It stands its", "watch on a bare", "tail, and screams"],
            ["before it flees.", "The scream is all", "the warning given."]],
"furret": [["Its burrows wind", "so far that none", "who follow return."],
           ["Some are old", "graves widened."]],
"hoothoot": [["It keeps the hour", "exactly, and hoots", "at each one."],
             ["The sleepless", "count their nights", "by its voice."]],
"noctowl": [["It turns its head", "and sees what the", "dark conceals."],
            ["It does not tell.", "It only watches."]],
"ledyba": [["It weeps a fluid", "that reeks, then", "huddles with its"],
           ["kind for warmth", "and for courage."]],
"ledian": [["It is said the", "spots upon its", "back mirror stars"],
           ["that died long", "before we looked."]],
"spinarak": [["It waits without", "moving for days,", "patient as debt."],
             ["The thread it", "spins is stronger", "than it looks."]],
"ariados": [["It fastens silk", "to its prey, then", "lets it wander"],
            ["home. It follows", "at its leisure."]],
"crobat": [["Four wings make", "it silent. You", "will not hear it"],
           ["until the blood", "is already gone."]],
"chinchou": [["Its lamps burn in", "the lightless", "deep, luring what"],
             ["is curious near", "enough to take."]],
"lanturn": [["Sailors name it", "the Deep-Lamp and", "steer well clear."],
            ["What its light", "draws up is not", "always its own."]],
# --- babies -----------------------------------------------------------------
"pichu": [["It cannot hold", "its own current", "and shocks itself"],
          ["when startled.", "It startles often."]],
"cleffa": [["Found only where", "stars have fallen.", "It remembers the"],
           ["sky it came from", "and grieves it."]],
"igglybuff": [["Its song is soft", "and short, and", "those who hear it"],
              ["sleep more deeply", "than they meant."]],
"togepi": [["The shell is said", "to hold good", "fortune. None has"],
           ["opened one to see", "and lived pleased."]],
"togetic": [["It seeks out the", "kind and shares", "their joy. It has"],
            ["not been seen here", "for many years."]],
"natu": [["It stares without", "blinking at what", "has not happened"],
         ["yet, and does not", "seem to like it."]],
"xatu": [["It stands all day", "unmoving. Some say", "it sees tomorrow"],
         ["and has decided", "not to interfere."]],
"mareep": [["Its fleece gathers", "charge until the", "air itself stings."],
           ["Shear it in storm", "and you will not", "shear again."]],
"flaaffy": [["Where the wool", "has worn away,", "the skin beneath"],
            ["glows. It is not", "a healthy light."]],
"ampharos": [["Its tail was once", "a beacon for", "ships. Now it"],
             ["burns for no one", "and burns still."]],
"bellossom": [["It dances when", "the rain comes.", "The old say the"],
              ["dance is a rite", "and not a joy."]],
"marill": [["Its tail floats,", "and so it cannot", "drown, though it"],
           ["has watched many", "others do so."]],
"azumarill": [["It hears through", "water what moves", "beneath. It hears"],
              ["the drowned turn", "in the current."]],
"sudowoodo": [["It stands as", "stone for years", "on end. Rain"],
              ["reveals it, and", "it hates the rain."]],
"politoed": [["Its call summons", "others from every", "marsh. None knows"],
             ["why they gather,", "nor what decides."]],
"hoppip": [["It cannot resist", "the wind and is", "carried far from"],
           ["where it began.", "It rarely returns."]],
"skiploom": [["Its bloom opens", "in warmth and", "shuts in cold."],
             ["Farmers read it", "as a barometer", "and a warning."]],
"jumpluff": [["It rides the wind", "across the sea", "and lands where"],
             ["it must. Many", "land in the water."]],
"aipom": [["Its tail is more", "clever than its", "hands, and takes"],
          ["what it pleases", "from the careless."]],
"sunkern": [["It is the least", "of all creatures", "and knows it."],
            ["It drops from", "trees to be seen", "at all."]],
"sunflora": [["It turns always", "to the light and", "will not look"],
             ["upon a shadow,", "not even its own."]],
"yanma": [["It sees all round", "at once without", "turning its head."],
          ["There is nowhere", "to stand unseen."]],
"wooper": [["It coats itself", "in poison film", "and sleeps in mud."],
           ["Touch it barehand", "and regret it."]],
"quagsire": [["It drifts open-", "mouthed and eats", "whatever enters."],
             ["It has no thought", "of hunger at all."]],
"espeon": [["It reads intent", "before the deed,", "and turns away"],
           ["from those whose", "hearts are foul."]],
"slowking": [["The crown upon it", "whispers, and it", "speaks what it"],
             ["is told. None ask", "who is the king."]],
"misdreavus": [["It feeds upon", "fright, and so it", "makes fright where"],
               ["none was. It has", "no other trade."]],
"wobbuffet": [["It suffers all", "and answers all,", "but never first."],
              ["Strike it and", "the blow returns", "twofold to you."]],
"girafarig": [["The head at its", "tail does not", "sleep, and bites"],
              ["whoever comes", "up from behind."]],
"pineco": [["It hangs still", "and bursts when", "jostled. Woodsmen"],
           ["have learned not", "to strike trees."]],
"dunsparce": [["It digs backward", "into the earth", "and vanishes."],
              ["Few have seen it.", "Fewer are believed"]],
"gligar": [["It glides down at", "the face, and", "clings there while"],
           ["the stinger works.", "It makes no sound."]],
"snubbull": [["Its scowl frights", "all who see it,", "which grieves it,"],
             ["for it wishes", "only to be near."]],
"granbull": [["It bites without", "warning and will", "not let go, though"],
             ["it is timid at", "heart and knows", "no better way."]],
"qwilfish": [["It swallows water", "until its spines", "stand out, then"],
             ["cannot swim, and", "waits to be found."]],
"shuckle": [["It hides in stone", "and lets the", "fruit it stores"],
            ["turn to liquor.", "The keeping is", "all it knows."]],
"heracross": [["It throws far", "stronger things", "than itself and"],
              ["takes their sap.", "It fights nightly", "for the same tree."]],
"teddiursa": [["It licks its paws", "sweet with stolen", "honey and sleeps"],
              ["content. The hive", "does not."]],
"ursaring": [["It marks the trees", "that bear food.", "The marks outlast"],
             ["the bear, and the", "forest remembers."]],
"slugma": [["Should its blood", "cool, it hardens", "and it dies."],
           ["So it never", "sleeps, and never", "may rest at all."]],
"magcargo": [["Its shell is", "crusted blood", "gone cold. The"],
             ["heat within is", "hotter than the", "flame outside."]],
"swinub": [["It roots in snow", "for what lies", "beneath, and finds"],
           ["food, and finds", "other things too."]],
"piloswine": [["Its coat hides", "its eyes. It goes", "by smell alone"],
              ["and charges what", "it cannot see."]],
"corsola": [["Its branches break", "and grow anew.", "The broken pieces"],
            ["are sold as charms", "against drowning."]],
"remoraid": [["It spits water", "hard enough to", "fell a bird in"],
             ["flight. It does", "not always eat", "what it fells."]],
"octillery": [["It takes a den", "and holds it,", "and what held it"],
              ["before is not", "seen again."]],
"delibird": [["It carries food", "in its tail and", "gives it away."],
             ["The lost are", "sometimes found", "beside its tracks."]],
"mantine": [["It leaps the", "waves and glides", "a hundred yards."],
            ["Sailors take it", "for an omen, and", "argue which."]],
"kingdra": [["It sleeps in the", "deepest trench", "and its waking"],
            ["stirs the whole", "sea to storm."]],
"phanpy": [["It sprays water", "over those it", "favours. Its"],
           ["strength is more", "than it knows."]],
"donphan": [["It rolls, and", "what stands in", "its way does not"],
            ["stand after.", "Houses have gone", "down before it."]],
"porygon2": [["It was made, not", "born. It learns", "what it was not"],
             ["taught, which", "troubles those", "who made it."]],
"stantler": [["Its antlers bend", "the air and show", "what is not there."],
             ["Travellers follow", "and are not seen", "again."]],
"smeargle": [["It paints with", "its tail in a", "fluid all its own."],
             ["The marks fade", "by morning, every", "one of them."]],
"tyrogue": [["It fights anything", "larger than", "itself, and loses,"],
            ["and rises, and", "fights again."]],
"hitmontop": [["It spins upon its", "head and strikes", "from every side"],
              ["at once. To watch", "it is to lose", "your footing."]],
"smoochum": [["It touches all", "things with its", "lips to know them,"],
             ["and remembers", "what it should", "not have learned."]],
"elekid": [["It spins its arms", "to make a charge", "and cannot stop"],
           ["once begun. Storms", "follow it about."]],
"magby": [["Its breath comes", "out as embers.", "Where it sleeps,"],
          ["nothing green", "grows after."]],
"miltank": [["Its milk mends", "the sick and the", "sorrowing alike."],
            ["The herd is kept", "close, and armed."]],
"blissey": [["It shares its egg", "with the suffering", "and asks nothing."],
            ["It is hunted for", "that very egg."]],
# --- legendaries ------------------------------------------------------------
"raikou": [["It runs before", "the storm and", "the storm obeys."],
           ["It was not always", "a beast, they say."]],
"entei": [["It is said a", "mountain burst", "the day it came."],
          ["Its every roar", "wakes the fire", "underneath."]],
"suicune": [["It runs the north", "wind and clears", "what water it"],
            ["touches. It will", "not touch ours."]],
"larvitar": [["It eats a whole", "mountain before", "it may see the"],
             ["sky. Few things", "want so much", "for so little."]],
"pupitar": [["Sealed in shell,", "it hurls itself", "about and cracks"],
            ["the stone it", "strikes. It is", "only impatient."]],
"lugia": [["It keeps the deep", "and does not", "rise. When it"],
          ["rises, so does", "the sea, and all", "upon it."]],
"ho_oh": [["Its wake is a", "rainbow. Those", "who see it are"],
          ["promised joy,", "and few live", "to collect it."]],
"celebi": [["It steps out of", "time into the", "wood, and the"],
           ["wood grows young.", "It has been seen", "in every age."]],
}

MAX_LINE = 18
