#!/usr/bin/env python3
"""
Gen 2 species emitter for Pokemon Purple -- the --apply half of the import.

Reads the validated roster from gen2_import.py and writes/patches every
species-indexed table. Run gen2_import.py --manifest first; this script trusts
that roster.

IDEMPOTENT: every patch is guarded by a marker comment, so re-running replaces
the generated block rather than appending a second copy.

Two numbering systems, never to be conflated:
  INTERNAL INDEX -> names, dex_order, cries, dex_entries, evos_moves
  DEX NUMBER     -> base_stats, palettes, menu_icons
"""
import os
import re
import sys
import shutil

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen2_import import (ROOT, REF, build_roster, front_sprite_path,
                         back_sprite_path)

MARK = "; === BEGIN GEN2 IMPORT (generated by tools/gen2_emit.py) ==="
MARKEND = "; === END GEN2 IMPORT ==="

# Files this script rewrites. Idempotency is achieved by restoring each from a
# pristine (pre-import) copy before patching, rather than by trying to detect
# and undo previous edits in place -- the gap-filling edits replace `const_skip`
# lines *in situ* and table appends land inside existing tables, so neither can
# be reliably identified after the fact. A first attempt without this restore
# silently double-applied (NUM_POKEMON_INDEXES came out 279 instead of 243).
PATCHED_FILES = [
    "gfx/pics.asm",
    "constants/pokemon_constants.asm",
    "constants/pokedex_constants.asm",
    "data/pokemon/names.asm",
    "data/pokemon/dex_order.asm",
    "data/pokemon/cries.asm",
    "data/pokemon/dex_entries.asm",
    "data/pokemon/evos_moves.asm",
    "data/pokemon/base_stats.asm",
    "data/pokemon/palettes.asm",
    "data/pokemon/menu_icons.asm",
    "data/pokemon/dex_text.asm",
]
PRISTINE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gen2_pristine")


def restore_pristine():
    for f in PATCHED_FILES:
        src = os.path.join(PRISTINE, f)
        if not os.path.exists(src):
            raise SystemExit(f"missing pristine copy: {src}")
        shutil.copyfile(src, os.path.join(ROOT, f))

# Near-universal Gen 1 TMs -- a conservative starting kit. Per-species TM
# curation is deliberately deferred; an empty tmhm is legal but leaves a mon
# unable to learn anything from TMs at all, which plays worse than a small set.
DEFAULT_TMHM = ["TOXIC", "RAGE", "MIMIC", "DOUBLE_TEAM", "REST", "SUBSTITUTE"]

# Level-up substitutes for evolution methods Gen 1's engine has no concept of.
# Friendship and held-item-trade evolutions are replaced with plain level
# thresholds (an explicit design decision, see CLAUDE.md); trade-evo final
# forms are instead made wild-catchable and get no chain at all.
FRIENDSHIP_EVO_LEVEL = {
    "PICHU": 12, "CLEFFA": 12, "IGGLYBUFF": 12, "GOLBAT": 30, "TOGEPI": 20,
}
NO_CHAIN = {"POLITOED", "SLOWKING", "KINGDRA"}


def read(p):
    return open(os.path.join(ROOT, p), encoding="utf-8").read()


def write(p, s):
    open(os.path.join(ROOT, p), "w", encoding="utf-8", newline="\n").write(s)


def strip_block(txt):
    """Remove a previously generated block so re-runs stay idempotent."""
    return re.sub(re.escape(MARK) + r".*?" + re.escape(MARKEND) + r"\n?",
                  "", txt, flags=re.S)


def table_entries(txt, start_pat, end_pat):
    """Split a one-entry-per-line table into (prefix, entries, suffix)."""
    lines = txt.split("\n")
    si = next(i for i, l in enumerate(lines) if re.search(start_pat, l))
    ei = next(i for i, l in enumerate(lines) if re.search(end_pat, l))
    body = lines[si + 1:ei]
    entries = [l for l in body if l.strip() and not l.strip().startswith(";")]
    return lines, si, ei, body, entries


def patch_table(path, start_pat, end_pat, expect, repl, appends):
    """repl: {1-based index -> new line}; appends: [line, ...] appended in order."""
    txt = read(path)
    lines, si, ei, body, entries = table_entries(txt, start_pat, end_pat)
    if len(entries) != expect:
        raise SystemExit(f"{path}: expected {expect} entries, found {len(entries)}")

    n = 0
    out_body = []
    for l in body:
        if l.strip() and not l.strip().startswith(";"):
            n += 1
            out_body.append(repl.get(n, l))
        else:
            out_body.append(l)
    out_body.extend(appends)
    new = lines[:si + 1] + out_body + lines[ei:]
    write(path, "\n".join(new))


# Gen 1 sprite PNGs are 8-bit grayscale (mode "L") using exactly the four DMG
# shades; the Makefile runs rgbgfx with --colors dmg, which hard-rejects any
# non-gray pixel. Gen 2 sprites are colour-paletted (mode "P") because Gen 2 is
# a colour game, so they must be flattened to those four grays. Ranking the
# source palette by luminance preserves the artist's shading structure (which
# pixel is highlight vs. shadow) instead of throwing it away.
DMG_LEVELS = [0, 85, 170, 255]


def convert_sprite(src, dst, size=None):
    from PIL import Image
    im = Image.open(src).convert("RGB")
    colors = {}
    for px in im.getdata():
        colors[px] = None
    ranked = sorted(colors, key=lambda c: 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2])
    if len(ranked) > 4:
        raise SystemExit(f"{src}: {len(ranked)} colours, DMG allows 4")
    # Always pin darkest->black and lightest->white; distribute any middles
    # across the remaining levels so a 3-colour sprite still reads correctly.
    if len(ranked) == 4:
        mapping = dict(zip(ranked, DMG_LEVELS))
    elif len(ranked) == 3:
        mapping = dict(zip(ranked, [0, 85, 255]))
    elif len(ranked) == 2:
        mapping = dict(zip(ranked, [0, 255]))
    else:
        mapping = {ranked[0]: 255}
    out = Image.new("L", im.size)
    out.putdata([mapping[px] for px in im.getdata()])
    if size:
        out = out.resize(size, Image.NEAREST)  # NEAREST keeps hard pixel edges
    out.save(dst)


def gen1_move_set():
    p = os.path.join(ROOT, "constants/move_constants.asm")
    return {m.group(1) for m in
            re.finditer(r"const\s+([A-Z_0-9]+)", open(p, encoding="utf-8").read())}


# Gen 2 renamed a couple of stones; anything not mapped here simply does not
# exist in Gen 1 (SUN_STONE, KINGS_ROCK, METAL_COAT, DRAGON_SCALE, ...).
ITEM_MAP = {
    "FIRE_STONE": "FIRE_STONE", "WATER_STONE": "WATER_STONE",
    "THUNDERSTONE": "THUNDER_STONE", "LEAF_STONE": "LEAF_STONE",
    "MOON_STONE": "MOON_STONE",
}

# Fallback level-up kits, used when filtering a Gen 2 learnset down to Gen 1
# moves leaves a species with almost nothing (70 of the moves Gen 2 teaches by
# level simply do not exist in Gen 1). Keeps every species playable.
TYPE_FALLBACK = {
    "NORMAL": [(1, "TACKLE"), (8, "GROWL"), (15, "QUICK_ATTACK"), (24, "BODY_SLAM")],
    "FIRE": [(1, "SCRATCH"), (9, "EMBER"), (18, "FIRE_SPIN"), (30, "FLAMETHROWER")],
    "WATER": [(1, "TACKLE"), (9, "WATER_GUN"), (18, "BUBBLEBEAM"), (30, "SURF")],
    "GRASS": [(1, "ABSORB"), (10, "VINE_WHIP"), (20, "MEGA_DRAIN"), (32, "RAZOR_LEAF")],
    "ELECTRIC": [(1, "THUNDERSHOCK"), (12, "THUNDER_WAVE"), (24, "THUNDERBOLT")],
    "BUG": [(1, "TACKLE"), (10, "LEECH_LIFE"), (20, "TWINEEDLE")],
    "POISON": [(1, "TACKLE"), (12, "POISON_STING"), (24, "SLUDGE")],
    "FLYING": [(1, "GUST"), (13, "WING_ATTACK"), (26, "DRILL_PECK")],
    "GROUND": [(1, "TACKLE"), (12, "SAND_ATTACK"), (24, "EARTHQUAKE")],
    "ROCK": [(1, "TACKLE"), (12, "ROCK_THROW"), (26, "ROCK_SLIDE")],
    "PSYCHIC_TYPE": [(1, "CONFUSION"), (15, "PSYBEAM"), (30, "PSYCHIC_M")],
    "ICE": [(1, "TACKLE"), (14, "AURORA_BEAM"), (28, "ICE_BEAM")],
    "FIGHTING": [(1, "TACKLE"), (13, "KARATE_CHOP"), (26, "SUBMISSION")],
    "GHOST": [(1, "LICK"), (15, "NIGHT_SHADE"), (28, "CONFUSE_RAY")],
    "DRAGON": [(1, "TACKLE"), (20, "DRAGON_RAGE"), (35, "HYPER_BEAM")],
}


def norm(name):
    """Labels in evos_attacks.asm are CamelCase ('Sentret', 'HoOh') while the
    species constants are SCREAMING_SNAKE ('SENTRET', 'HO_OH'). Normalising both
    to alphanumerics-uppercased makes them comparable. Skipping this silently
    matched nothing, so every species fell through to its type fallback kit --
    a wrong-but-plausible result that builds cleanly."""
    return re.sub(r"[^A-Z0-9]", "", name.upper())


def parse_gen2_evos_attacks():
    """-> {normalised species name: (evolutions, learnset)}"""
    p = os.path.join(REF, "data/pokemon/evos_attacks.asm")
    out, cur = {}, None
    for line in open(p, encoding="utf-8"):
        m = re.match(r"^([A-Za-z0-9_]+)EvosAttacks:", line)
        if m:
            cur = norm(m.group(1))
            out[cur] = ([], [])
            continue
        if cur is None:
            continue
        s = line.strip()
        m = re.match(r"db\s+(EVOLVE_[A-Z_]+),\s*(.+)", s)
        if m:
            out[cur][0].append((m.group(1), [a.strip() for a in m.group(2).split(",")]))
            continue
        m = re.match(r"db\s+(\d+),\s*([A-Z_0-9]+)\s*$", s)
        if m:
            out[cur][1].append((int(m.group(1)), m.group(2)))
    return out


def convert_evolutions(s, raw_evos, valid_targets, g1moves):
    """Gen 2 evolution methods -> Gen 1's three, applying the agreed substitutions."""
    lines = []
    if s["const"] in NO_CHAIN:
        return lines  # wild-catchable final form only, by design decision
    for method, args in raw_evos:
        target = args[-1]
        # Only port a chain if the target actually exists in this ROM. Targets
        # that were excluded (Dark/Steel) or that are Gen 1 species whose own
        # evos entries we do not regenerate would dangle otherwise.
        if target not in valid_targets:
            continue
        if method == "EVOLVE_LEVEL":
            lines.append(f"\tdb EVOLVE_LEVEL, {args[0]}, {target}")
        elif method == "EVOLVE_ITEM":
            g1item = ITEM_MAP.get(args[0])
            if g1item:
                lines.append(f"\tdb EVOLVE_ITEM, {g1item}, 1, {target}")
            else:
                # Stone has no Gen 1 equivalent (SUN_STONE etc.) -> level up.
                lines.append(f"\tdb EVOLVE_LEVEL, 30, {target}")
        elif method == "EVOLVE_TRADE":
            # Gen 1 trade evolution carries a min-level byte and no held item.
            lines.append(f"\tdb EVOLVE_TRADE, 1, {target}")
        elif method == "EVOLVE_HAPPINESS":
            lvl = FRIENDSHIP_EVO_LEVEL.get(s["const"], 20)
            lines.append(f"\tdb EVOLVE_LEVEL, {lvl}, {target}")
        elif method == "EVOLVE_STAT":
            # Tyrogue's atk/def comparison has no Gen 1 analogue; plain level.
            lines.append(f"\tdb EVOLVE_LEVEL, {args[0]}, {target}")
    return lines


def convert_learnset(s, raw_moves, g1moves):
    kept = [(lvl, mv) for lvl, mv in raw_moves if mv in g1moves and lvl > 1]
    if len(kept) < 3:
        base = TYPE_FALLBACK.get(s["type1"], TYPE_FALLBACK["NORMAL"])
        have = {mv for _, mv in kept}
        for lvl, mv in base:
            if lvl > 1 and mv in g1moves and mv not in have:
                kept.append((lvl, mv))
    return sorted(set(kept))[:12]


def level1_moves(s, raw_moves, g1moves):
    mv = [m for lvl, m in raw_moves if lvl == 1 and m in g1moves]
    if not mv:
        base = TYPE_FALLBACK.get(s["type1"], TYPE_FALLBACK["NORMAL"])
        mv = [m for lvl, m in base if lvl == 1 and m in g1moves] or ["TACKLE"]
    mv = mv[:4]
    return mv + ["NO_MOVE"] * (4 - len(mv))


def gen1_name(const):
    return {"HO_OH": "HO-OH", "PORYGON2": "PORYGON2"}.get(const, const)


def convert_dex_text(slug, label):
    """Gen 2 dex prose -> Gen 1 text macros (near-identical dialects)."""
    p = os.path.join(REF, f"data/pokemon/dex_entries/gold/{slug}.asm")
    body = []
    for line in open(p, encoding="utf-8"):
        s = line.strip()
        m = re.match(r'(db|next|page)\s+"(.*)"', s)
        if not m:
            continue
        kind, content = m.group(1), m.group(2)
        if kind == "db":
            continue  # first db is the species category, handled separately
        body.append((kind, content))
    # the first prose line is a `db "..."` that follows the `dw height, weight`
    prose = []
    seen_hw = False
    for line in open(p, encoding="utf-8"):
        s = line.strip()
        if s.startswith("dw "):
            seen_hw = True
            continue
        if not seen_hw:
            continue
        m = re.match(r'(db|next|page)\s+"(.*)"', s)
        if m:
            prose.append((m.group(1), m.group(2)))
    if not prose:
        return f'{label}::\n\ttext "No data."\n\tdex\n'
    out = [f"{label}::"]
    for i, (kind, content) in enumerate(prose):
        content = content.rstrip("@")
        macro = "text" if i == 0 else kind
        out.append(f'\t{macro} "{content}"')
    out.append("\tdex")
    return "\n".join(out) + "\n"


def main():
    # MUST restore before build_roster(): the roster's index assignment is
    # derived by scanning constants/pokemon_constants.asm for `const_skip`
    # gaps, so running against an already-patched tree finds fewer gaps, pushes
    # more species into the appended range, and inflates NUM_POKEMON_INDEXES
    # (observed: 279 instead of 243).
    restore_pristine()
    print(f"restored {len(PATCHED_FILES)} files from pristine copies")
    eligible, excluded, gaps = build_roster()
    NIDX = max(s["index"] for s in eligible)
    NDEX = max(s["dex"] for s in eligible)
    by_index = {s["index"]: s for s in eligible}
    appended = sorted([s for s in eligible if s["slot"] == "appended"],
                      key=lambda s: s["index"])
    in_dex_order = sorted(eligible, key=lambda s: s["dex"])

    print(f"emitting {len(eligible)} species; NUM_POKEMON_INDEXES={NIDX} "
          f"NUM_POKEMON={NDEX}")

    # ---- 1. sprites -------------------------------------------------------
    for s in eligible:
        convert_sprite(front_sprite_path(s["slug"]),
                       os.path.join(ROOT, f"gfx/pokemon/front/{s['slug']}.png"))
        # Gen 1 back pics are uniformly 32x32; Gen 2's are uniformly 48x48.
        convert_sprite(back_sprite_path(s["slug"]),
                       os.path.join(ROOT, f"gfx/pokemon/back/{s['slug']}b.png"),
                       size=(32, 32))
    print(f"  sprites: {len(eligible)} front + {len(eligible)} back converted")

    # ---- 2. gfx/pics.asm --------------------------------------------------
    txt = strip_block(read("gfx/pics.asm"))
    # Floating sections (no explicit bank) so the linker can bin-pack them;
    # layout.link pins every hand-written section with no slack. Sprite data for
    # 89 species is ~42KB, which cannot live in one 16KB bank, so it is split
    # across several sections. PER_SECTION is chosen so even a worst-case run of
    # max-size pics (637B front + 198B back) stays under a bank.
    PER_SECTION = 15
    blk = [MARK]
    for i, s in enumerate(eligible):
        if i % PER_SECTION == 0:
            blk += ["", f'SECTION "Pics Gen2 {i // PER_SECTION + 1}", ROMX', ""]
        blk.append(f'{s["label"]}PicFront:: INCBIN "gfx/pokemon/front/{s["slug"]}.pic"')
        blk.append(f'{s["label"]}PicBack::  INCBIN "gfx/pokemon/back/{s["slug"]}b.pic"')
    blk.append(MARKEND)
    write("gfx/pics.asm", txt.rstrip("\n") + "\n\n" + "\n".join(blk) + "\n")

    # ---- 2b. pic bank lookup table ---------------------------------------
    # home/pics.asm used to pick a mon's sprite ROM bank from hardcoded index
    # RANGES (index < $1F -> "Pics 1", < $4A -> "Pics 2", ...). That cannot
    # describe the imported species: their indexes are scattered through the
    # reclaimed gaps, while their sprites live in separate "Pics Gen2 N"
    # sections in entirely different banks. Every new species therefore loaded
    # garbage from a vanilla Pics bank. Replaced with this table, which is
    # exact for every species and removes the range fragility outright.
    idx_to_const = {}
    val = -1
    for line in open(os.path.join(PRISTINE, "constants/pokemon_constants.asm"),
                     encoding="utf-8"):
        s = line.strip()
        if s.startswith("const_def"):
            val = -1
            continue
        if s.startswith("const_next"):
            val = int(re.search(r"\$([0-9A-Fa-f]+)", s).group(1)) - 1
            continue
        if s.startswith("const_skip"):
            val += 1
            continue
        m = re.match(r"const\s+([A-Z_0-9]+)", s)
        if m:
            val += 1
            idx_to_const[val] = m.group(1)
    const_to_idx = {v: k for k, v in idx_to_const.items()}

    def vanilla_pic_section(i):
        """Mirror of the thresholds home/pics.asm used to hardcode."""
        if i < const_to_idx["TANGELA"] + 1:
            return '"Pics 1"'
        if i < const_to_idx["MOLTRES"] + 1:
            return '"Pics 2"'
        if i < const_to_idx["BEEDRILL"] + 2:
            return '"Pics 3"'
        if i < const_to_idx["STARMIE"] + 1:
            return '"Pics 4"'
        return '"Pics 5"'

    gen2_section = {}
    for i, sp in enumerate(eligible):
        gen2_section[sp["index"]] = f'"Pics Gen2 {i // PER_SECTION + 1}"'

    rows = ["; Generated by tools/gen2_emit.py -- do not edit by hand.",
            "; Sprite ROM bank for each species, indexed by INTERNAL INDEX.",
            "; MEW and the fossil/ghost pics are special-cased in",
            "; home/pics.asm before this table is consulted.",
            "MonPicBanks::",
            "\ttable_width 1",
            "\tdb 0 ; $00 NO_MON (no pic)"]
    for i in range(1, NIDX + 1):
        if i in gen2_section:
            sect, who = gen2_section[i], by_index[i]["const"]
        else:
            sect, who = vanilla_pic_section(i), idx_to_const.get(i, "unused")
        rows.append(f"\tdb BANK({sect}) ; ${i:02X} {who}")
    rows.append(f"\tassert_table_length NUM_POKEMON_INDEXES + 1")
    write("data/pokemon/pic_banks.asm", "\n".join(rows) + "\n")
    print(f"  pic bank table: {NIDX + 1} entries")

    # ---- 3. base_stats/<slug>.asm ----------------------------------------
    g1moves = gen1_move_set()
    raw = parse_gen2_evos_attacks()
    # A valid evolution target is ANY species that exists in this ROM: the newly
    # imported ones plus every vanilla Gen 1 species. Restricting this to the new
    # roster alone silently dropped the baby-Pokemon chains (Pichu->Pikachu,
    # Cleffa->Clefairy, Igglybuff->Jigglypuff), whose targets are Gen 1 mons.
    # Species excluded for typing (Steelix, Scizor, ...) are in neither set and
    # so are still correctly rejected, leaving those chains unbuilt.
    gen1_consts = set(re.findall(
        r"const\s+([A-Z_0-9]+)",
        open(os.path.join(PRISTINE, "constants/pokemon_constants.asm"),
             encoding="utf-8").read()))
    const_to_species = {sp["const"]: sp for sp in eligible}
    valid_targets = set(const_to_species) | gen1_consts
    missing = [sp["const"] for sp in eligible if norm(sp["const"]) not in raw]
    if missing:
        raise SystemExit(f"no evos/attacks data matched for: {missing}")
    for s in eligible:
        r_evo, r_learn = raw.get(norm(s["const"]), ([], []))
        s["evos"] = convert_evolutions(s, r_evo, valid_targets, g1moves)
        s["learn"] = convert_learnset(s, r_learn, g1moves)
        s["lv1"] = level1_moves(s, r_learn, g1moves)
    for s in eligible:
        t1, t2 = s["type1"], s["type2"]
        lines = [
            f'\tdb DEX_{s["const"]} ; pokedex id', "",
            f'\tdb {s["hp"]:3d}, {s["atk"]:3d}, {s["dfn"]:3d}, {s["spd"]:3d}, {s["special"]:3d}',
            "\t;   hp  atk  def  spd  spc", "",
            f"\tdb {t1}, {t2} ; type",
            f'\tdb {s["catch"]} ; catch rate',
            f'\tdb {s["base_exp"]} ; base exp', "",
            f'\tINCBIN "gfx/pokemon/front/{s["slug"]}.pic", 0, 1 ; sprite dimensions',
            f'\tdw {s["label"]}PicFront, {s["label"]}PicBack', "",
            f'\tdb {", ".join(s["lv1"])} ; level 1 learnset',
            f'\tdb {s["growth"]} ; growth rate', "",
            "\t; tm/hm learnset",
            "\ttmhm " + ", ".join(DEFAULT_TMHM),
            "\t; end", "",
            "\tdb 0 ; padding", "",
        ]
        write(f'data/pokemon/base_stats/{s["slug"]}.asm', "\n".join(lines))
    print(f"  base stats: {len(eligible)} files written")

    # ---- 4. constants/pokemon_constants.asm (internal index) -------------
    txt = strip_block(read("constants/pokemon_constants.asm"))
    # Same counter convention as find_gap_indices: `const_def` starts at 0 and
    # NO_MON takes index $00, so the counter sits at -1 before the first const.
    out, val = [], -1
    for line in txt.split("\n"):
        s = line.strip()
        if s.startswith("const_def"):
            val = -1
        elif s.startswith("const_next"):
            val = int(re.search(r"\$([0-9A-Fa-f]+)", s).group(1)) - 1
        elif s.startswith("const_skip"):
            val += 1
            if val in by_index:
                sp = by_index[val]
                out.append(f'\tconst {sp["const"]:<16} ; ${val:02X}')
                continue
        elif s.startswith("const ") or s.startswith("const\t"):
            val += 1
        if "DEF NUM_POKEMON_INDEXES" in line:
            blk = [MARK]
            for sp in appended:
                blk.append(f'\tconst {sp["const"]:<16} ; ${sp["index"]:02X}')
            blk.append(MARKEND)
            out.extend(blk)
        out.append(line)
    write("constants/pokemon_constants.asm", "\n".join(out))

    # ---- 5. constants/pokedex_constants.asm (dex number) -----------------
    txt = strip_block(read("constants/pokedex_constants.asm"))
    out = []
    for line in txt.split("\n"):
        if "DEF NUM_POKEMON " in line or line.startswith("DEF NUM_POKEMON"):
            out.append(MARK)
            for sp in in_dex_order:
                out.append(f'\tconst DEX_{sp["const"]:<12} ; {sp["dex"]}')
            out.append(MARKEND)
        out.append(line)
    write("constants/pokedex_constants.asm", "\n".join(out))

    # ---- 6. internal-index tables ----------------------------------------
    OLD_IDX = 190
    patch_table("data/pokemon/names.asm", r"table_width", r"assert_table_length",
                OLD_IDX,
                {s["index"]: f'\tdname "{gen1_name(s["const"])}"' for s in eligible},
                [f'\tdname "{gen1_name(s["const"])}"' for s in appended])

    patch_table("data/pokemon/dex_order.asm", r"table_width", r"assert_table_length",
                OLD_IDX,
                {s["index"]: f'\tdb DEX_{s["const"]}' for s in eligible},
                [f'\tdb DEX_{s["const"]}' for s in appended])

    patch_table("data/pokemon/cries.asm", r"; base cry, pitch, length",
                r"assert_table_length", OLD_IDX,
                {s["index"]: f'\tmon_cry SFX_CRY_{s["dex"] % 25:02d}, '
                             f'${(s["atk"] * 7) % 256:02X}, ${0x80:02X} ; {s["const"]}'
                 for s in eligible},
                [f'\tmon_cry SFX_CRY_{s["dex"] % 25:02d}, '
                 f'${(s["atk"] * 7) % 256:02X}, ${0x80:02X} ; {s["const"]}'
                 for s in appended])

    patch_table("data/pokemon/dex_entries.asm", r"table_width", r"assert_table_length",
                OLD_IDX,
                {s["index"]: f'\tdw {s["label"]}DexEntry' for s in eligible},
                [f'\tdw {s["label"]}DexEntry' for s in appended])

    patch_table("data/pokemon/evos_moves.asm", r"table_width", r"assert_table_length",
                OLD_IDX,
                {s["index"]: f'\tdw {s["label"]}EvosMoves' for s in eligible},
                [f'\tdw {s["label"]}EvosMoves' for s in appended])

    # ---- 7. dex-number tables --------------------------------------------
    patch_table("data/pokemon/base_stats.asm", r"table_width", r"assert_table_length",
                150, {},
                [f'INCLUDE "data/pokemon/base_stats/{s["slug"]}.asm"'
                 for s in in_dex_order])

    patch_table("data/pokemon/palettes.asm", r"table_width", r"assert_table_length",
                152, {},
                [f'\tdb {s["pal"]:<14} ; {s["const"]}' for s in in_dex_order])

    patch_table("data/pokemon/menu_icons.asm", r"nybble_array", r"end_nybble_array",
                151, {},
                [f'\tnybble {s["icon"]:<14} ; {s["const"]}' for s in in_dex_order])

    # ---- 8. evos/moves + dex entry + dex text data blocks -----------------
    evo_by_const = {s["const"]: s for s in eligible}
    txt = strip_block(read("data/pokemon/evos_moves.asm"))
    blk = [MARK]
    for s in eligible:
        blk.append(f'{s["label"]}EvosMoves:')
        blk.append("; Evolutions")
        blk.extend(s["evos"])
        blk.append("\tdb 0 ; no more evolutions")
        blk.append("; Learnset")
        for lvl, mv in s["learn"]:
            blk.append(f"\tdb {lvl}, {mv}")
        blk.append("\tdb 0 ; no more level-up moves")
        blk.append("")
    blk.append(MARKEND)
    write("data/pokemon/evos_moves.asm", txt.rstrip("\n") + "\n\n" + "\n".join(blk) + "\n")

    txt = strip_block(read("data/pokemon/dex_entries.asm"))
    blk = [MARK]
    for s in eligible:
        cat, ft, inch, wt = s["dexinfo"]
        blk.append(f'{s["label"]}DexEntry:')
        blk.append(f'\tdb "{cat}@"')
        blk.append(f"\tdb {ft},{inch}")
        blk.append(f"\tdw {wt}")
        blk.append(f'\ttext_far _{s["label"]}DexEntry')
        blk.append("\ttext_end")
        blk.append("")
    blk.append(MARKEND)
    write("data/pokemon/dex_entries.asm", txt.rstrip("\n") + "\n\n" + "\n".join(blk) + "\n")

    txt = strip_block(read("data/pokemon/dex_text.asm"))
    blk = [MARK,
           "; NOTE: prose here is converted straight from the Gen 2 source and has",
           "; NOT yet had the Victorian-gothic rewrite pass applied (see CLAUDE.md).",
           ";",
           "; Opening a new floating SECTION here (rather than letting this land in",
           '; the pinned "Pokédex Text" section this file is included into) because',
           "; ~8KB of new prose overflows that bank by 0x1B4E. This is safe ONLY",
           "; because dex prose is reached through `text_far`, a bank-aware far",
           "; pointer -- unlike PokedexEntryPointers/EvosMovesPointerTable, whose",
           "; near `dw` pointers force their data to stay in the reader's bank.",
           'SECTION "Pokédex Text Gen2", ROMX',
           ""]
    for s in eligible:
        blk.append(convert_dex_text(s["slug"], f'_{s["label"]}DexEntry'))
    blk.append(MARKEND)
    write("data/pokemon/dex_text.asm", txt.rstrip("\n") + "\n\n" + "\n".join(blk) + "\n")

    print("  tables patched; done")


if __name__ == "__main__":
    main()
