#!/usr/bin/env python3
"""
Export every species' front/back battle sprite into the Godot port -- the
last item on Phase 1 of the port plan.

    python tools/godot_export_sprites.py

Reads the Godot project's own data/species.json (already generated by
godot_export_data.py) as the authoritative list of species + slugs, rather
than re-deriving indexes from the ROM constants a second time -- species.json
already resolved the "two numbering systems" trap once; there's no reason to
risk re-solving it slightly differently here.

Source art is gfx/pokemon/front/<name>.png / gfx/pokemon/back/<name>b.png,
already grayscale-quantized to the DMG's 4 shades (confirmed by inspection --
these are the same source PNGs rgbgfx compiles into the ROM's real sprite
data, not a separate asset). Recolored with the same DMG lookup used
everywhere else in this pipeline (godot_export.py's export_sprite), with the
lightest shade keyed transparent so it composites over a battle background.

Filenames don't always match a species' slug exactly (Mr. Mime's source file
is literally "mr.mime.png", not "mrmime.png") -- rather than special-casing
that one name, every source filename and every species slug are matched
through the same normalized (alphanumeric-only, lowercased) key, the same
technique godot_export.py already uses for tileset name aliases.
"""
import json
import os
import re

from godot_export import DMG, ROOT, GODOT

FRONT_SRC = os.path.join(ROOT, "gfx", "pokemon", "front")
BACK_SRC = os.path.join(ROOT, "gfx", "pokemon", "back")
FRONT_DEST = os.path.join(GODOT, "assets", "sprites", "pokemon", "front")
BACK_DEST = os.path.join(GODOT, "assets", "sprites", "pokemon", "back")


def _norm(name):
    return re.sub(r"[^a-z0-9]", "", name.lower())


def _index(dir_path, strip_suffix=""):
    """normalized name -> real filename (no extension), for every .png in dir_path."""
    out = {}
    for fname in os.listdir(dir_path):
        if not fname.endswith(".png"):
            continue
        stem = fname[:-4]
        key = _norm(stem)
        if strip_suffix and key.endswith(strip_suffix):
            key = key[: -len(strip_suffix)]
        out[key] = stem
    return out


def _convert(src_path, dest_path):
    from PIL import Image

    im = Image.open(src_path).convert("L")
    shades = sorted(set(im.getdata()), reverse=True)  # lightest first
    lut = {v: DMG[min(i, 3)] for i, v in enumerate(shades)}
    out = Image.new("RGBA", im.size)
    px = []
    for p in im.getdata():
        r, g, b = lut[p]
        px.append((r, g, b, 0) if p == shades[0] else (r, g, b, 255))
    out.putdata(px)
    out.save(dest_path)


def main():
    species = json.load(open(os.path.join(GODOT, "data", "species.json"), encoding="utf-8"))
    front_index = _index(FRONT_SRC)
    back_index = _index(BACK_SRC, strip_suffix="b")

    os.makedirs(FRONT_DEST, exist_ok=True)
    os.makedirs(BACK_DEST, exist_ok=True)

    done = 0
    missing = []
    for const, s in species.items():
        slug = s["slug"]
        key = _norm(slug)

        front_stem = front_index.get(key)
        back_stem = back_index.get(key)
        if not front_stem or not back_stem:
            missing.append((const, slug))
            continue

        _convert(os.path.join(FRONT_SRC, front_stem + ".png"),
                 os.path.join(FRONT_DEST, slug + ".png"))
        _convert(os.path.join(BACK_SRC, back_stem + ".png"),
                 os.path.join(BACK_DEST, slug + ".png"))
        done += 1

    print(f"Exported {done}/{len(species)} species' front+back sprites")
    if missing:
        print(f"{len(missing)} missing a source sprite:")
        for const, slug in missing:
            print(f"  {const} (slug={slug})")


if __name__ == "__main__":
    main()
